### ISSUE TITLE
Label Error

### ISSUE THREAD

**Issue by zhausong** [cavaliercoder/alexandria-dashboard#1]
```
WARN  2015/08/05 12:24:48 i18n.go:53: Unsupported default language for locale 'en-US' and message 'label.save'
TRACE 2015/08/05 12:24:48 i18n.go:183: Unable to read locale cookie with name 'ALEX_LANG': http: named cookie not present
TRACE 2015/08/05 12:24:48 i18n.go:149: Found Accept-Language header value: zh-CN
```

parent is NULL

```
var atts = parent ? parent.children : citype.attributes;
```

![image](https://cloud.githubusercontent.com/assets/3434306/9078256/c67bc19e-3b6d-11e5-9c47-b8c23ce2f024.png)

**Comment by cavaliercoder** [comment]
Hi, thanks for logging these issues. As noted in the readme, this project is in its infancy and not stable or ready for deployment. The master branch is rife with issues and constantly changing. I have not yet released a stable version.

While I'm interested in errors that may cause long term problems, I'm more interested in finding people who are willing to participate in the project and start developing features to completion

I can confidently say these sorts of bugs will be fairly frequent in the immediate future!

That said, thank you for installing Alexandria and giving it a try. I'm sorry it couldn't give you more value sooner. If you would like to submit pull-requests and ideas, that would be greatly appreciated.
